import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavbarAuth from "@/components/layout/Navbar";
import AuthProvider from "@/components/auth-provider";
import Footer from "@/components/layout/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
      <AuthProvider>
        <NavbarAuth></NavbarAuth>  
        {children}
        <Footer></Footer>
        </AuthProvider>
      
     
      </body>
    </html>
  );
}
